💄 (create-symposium): halfsheet modal with text field and button
nilvng/theredbookapp pull request #1
Opened 2023-04-15 04:15 UTC by nilvng

2023-04-20 12:54 UTC, thesupersonic16 requested changes
I have noticed some easy to fixed issues and provided some suggestion code. However the keyboard does not fully close properly, not sure if its an issue with Android as I assume you only tested it on iOS.

2023-04-20 12:54 UTC, thesupersonic16 commented on Symposium/BasicModal.jsx
> +                                        style={{ width: "100%" }}
The text for the text box gets cut off on the top. I assume just adding a little bit of margin should be fine as suggested.

```suggestion
                                        style={{ width: "100%", marginTop: 4 }}
```
![image](https://user-images.githubusercontent.com/25761885/233370361-6dae4848-e0c1-4313-86b8-b075a4613039.png)

2023-04-20 12:54 UTC, thesupersonic16 commented on Symposium/BasicModal.jsx
> +                                        label='Enter your subject...'
Please use `placeholder` instead of `label` so that text doesn't overlap.
```suggestion
                                        placeholder='Enter your subject...'
```
![image](https://user-images.githubusercontent.com/25761885/233370932-6d6a4ed4-a0bc-4ad2-b54a-0c7339a66ecd.png)

2023-04-21 06:49 UTC, nilvng commented on Symposium/BasicModal.jsx
> +                                        label='Enter your subject...'
what is the issue you meant? adding margin seems to be the trick to me

2023-04-21 06:54 UTC, nilvng commented on Symposium/BasicModal.jsx
> +                                        label='Enter your subject...'
<img height="440" src="https://user-images.githubusercontent.com/55075292/233562657-8ebccaeb-735a-4170-ba0a-f1bf1291a1e9.jpeg"/>

2023-04-21 06:56 UTC, thesupersonic16 commented on Symposium/BasicModal.jsx
> +                                        label='Enter your subject...'
When you write text and deselect the text box, both the label and the entered text overlap.

2023-04-21 07:52 UTC, nilvng commented on Symposium/BasicModal.jsx
> +                                        label='Enter your subject...'
resolved in the latest commit! thanks Mark!

2023-04-21 09:25 UTC, thesupersonic16 approved these changes
LGTM

2023-04-21 09:25 UTC, merged